services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: andruha_admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: da_project
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  generator:
    build: ./generator
    depends_on:
      - db
    environment:
      DB_HOST: db
      POSTGRES_DB: da_project
      POSTGRES_USER: andruha_admin
      POSTGRES_PASSWORD: 123
    volumes:
      - ./images:/app/images

  redis:
    image: redis:5.0-alpine

  redash:
    image: redash/redash:10.1.0.b50633
    command: server
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    environment:
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://andruha_admin:123@db/postgres"
      REDASH_COOKIE_SECRET: "123"
      REDASH_WEB_WORKERS: 4

  worker:
    image: redash/redash:10.1.0.b50633
    command: worker
    depends_on:
      - db
      - redis
    environment:
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://andruha_admin:123@db/postgres"
      REDASH_COOKIE_SECRET: "123"
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 1

volumes:
  postgres_data: